// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwqb5e3WUPl__xk9bSWUTtEVM3A28wmjk',
    appId: '1:499425462708:web:b2287a00059efb2dfe0ae1',
    messagingSenderId: '499425462708',
    projectId: 'flutter-study-01',
    authDomain: 'flutter-study-01.firebaseapp.com',
    storageBucket: 'flutter-study-01.appspot.com',
    measurementId: 'G-FP97QBYSM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKVEXSMVGKOyxB9k10rmY9_Zqcl4L_yl0',
    appId: '1:499425462708:android:4802dbccb70f7169fe0ae1',
    messagingSenderId: '499425462708',
    projectId: 'flutter-study-01',
    storageBucket: 'flutter-study-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe3Rk7YF_Q2l7YMkR8AgJKsV_J9c8zsE4',
    appId: '1:499425462708:ios:81ef182cc1343141fe0ae1',
    messagingSenderId: '499425462708',
    projectId: 'flutter-study-01',
    storageBucket: 'flutter-study-01.appspot.com',
    iosClientId: '499425462708-4vhes1c272lfir166g21l845slbl0j64.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe3Rk7YF_Q2l7YMkR8AgJKsV_J9c8zsE4',
    appId: '1:499425462708:ios:81ef182cc1343141fe0ae1',
    messagingSenderId: '499425462708',
    projectId: 'flutter-study-01',
    storageBucket: 'flutter-study-01.appspot.com',
    iosClientId: '499425462708-4vhes1c272lfir166g21l845slbl0j64.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );
}
